### ISSUE TITLE
Module published on Registry doesn't have latest fixes

### ISSUE THREAD

**Issue by Nathan-Gauci-Kasna** [GoogleCloudPlatform/terraform-google-cloud-workflows#15]
The version of this module published on the Terraform Registry: https://registry.terraform.io/modules/GoogleCloudPlatform/cloud-workflows/google/latest doesn't work for scheduled triggers because it outdated. 

Also, the examples given in the readme https://github.com/GoogleCloudPlatform/terraform-google-cloud-workflows/blob/7b9b07b51bf77352b94bec80231c8cead7f89c6f/README.md?plain=1#L16 are incorrect because this Module is in the GoogleCloudPlatform org not the terraform-google-modules one

**Comment by burnzy** [comment]
I think there just hasn't been a new release created yet from the main branch. The current release 0.1.0 has fatal bugs in the `locals` that cause the module to break. Looks like they've been fixed in main branch, but no patch release created yet.

For example:

Release 0.1.0:
https://github.com/GoogleCloudPlatform/terraform-google-cloud-workflows/blob/2fcb08fe79bcda517b3b3b37f2d19cd7c23d4984/main.tf#L34


main:
https://github.com/GoogleCloudPlatform/terraform-google-cloud-workflows/blob/fc4da117fad8a466438ff350ce97eef6dcf5dd65/main.tf#L34

**Comment by ddlenz** [comment]
When is a new release expected?
